movieSet/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('contact/', include("contact.urls")),
    path("", include("movies.urls")),
]

admin.autodiscover()
admin.site.enable_nav_sidebar = False

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.MoviesView.as_view()),
    path("search/", views.Search.as_view(), name='search'),
    path("filter/", views.FilterMoviesView.as_view(), name='filter'),
    path("<slug:slug>/", views.MovieDetailView.as_view(), name="movie_detail"),
    path("review/<int:pk>/", views.AddReview.as_view(), name="add_review"),
    path("actor/<str:slug>/", views.ActorView.as_view(), name="actor_detail"),

]

movies/models.py
from datetime import date

from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField("Category", max_length=150)
    description = models.TextField("Description")
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"


class Actor(models.Model):
    name = models.CharField("Name", max_length=100)
    age = models.PositiveSmallIntegerField("Age", default=0)
    description = models.TextField("Description")
    image = models.ImageField("Image", upload_to="actors/")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('actor_detail', kwargs={"slug": self.name})

    class Meta:
        verbose_name = "Actor and director"
        verbose_name_plural = "Actors and directors"


class Genre(models.Model):
    name = models.CharField("Name", max_length=100)
    description = models.TextField("Description")
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Genre"
        verbose_name_plural = "Genres"


class Movie(models.Model):
    title = models.CharField("Title", max_length=100)
    tagline = models.CharField("Tagline", max_length=100, default="")
    description = models.TextField("Description")
    poster = models.ImageField("Poster", upload_to="movies/")
    year = models.PositiveSmallIntegerField("Release date", default=2022)
    country = models.CharField("Country", max_length=30)
    directors = models.ManyToManyField(Actor, verbose_name="director", related_name="film_director")
    actors = models.ManyToManyField(Actor, verbose_name="actors", related_name="film_actor")
    genres = models.ManyToManyField(Genre, verbose_name="genres")
    world_premiere = models.DateField("World premiere", default=date.today)
    budget = models.PositiveIntegerField("Budget", default=0, help_text="enter the amount in dollars")
    fees_in_usa = models.PositiveIntegerField("Fees in USA", default=0, help_text="enter the amount in dollars")
    fees_in_world = models.PositiveIntegerField("Fees in World", default=0, help_text="enter the amount in dollars")
    category = models.ForeignKey(Category, verbose_name="category", on_delete=models.SET_NULL, null=True)
    url = models.SlugField(max_length=160, unique=True)
    draft = models.BooleanField("Draft", default=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("movie_detail", kwargs={"slug": self.url})

    def get_review(self):
        return self.reviews_set.filter(parent__isnull=True)

    class Met:
        verbose_name = "Movie"
        verbose_name_plural = "Movies"


class MovieShots(models.Model):
    title = models.CharField("Title", max_length=100)
    description = models.TextField("Description")
    image = models.ImageField("Image", upload_to="movie_shots/")
    movie = models.ForeignKey(Movie, verbose_name="Movie", on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Shot from movie"
        verbose_name_plural = "Shots from movie"


class Reviews(models.Model):
    email = models.EmailField()
    name = models.CharField("Name", max_length=100)
    text = models.TextField("Message", max_length=5000)
    parent = models.ForeignKey("self", verbose_name="Parent", on_delete=models.SET_NULL, blank=True, null=True)
    movie = models.ForeignKey(Movie, verbose_name="movie", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} - {self.movie}"

    class Meta:
        verbose_name = "Review"
        verbose_name_plural = "Reviews"

movies/forms.py
from django import forms
from .models import Reviews


class ReviewForm(forms.ModelForm):
    """Form of Reviews"""
    class Meta:
        model = Reviews
        fields = ("name", "email", "text")
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control border"}),
            "email": forms.EmailInput(attrs={"class": "form-control border"}),
            "text": forms.Textarea(attrs={"class": "form-control border"})
        }

movies/views.py
from django.db.models import Q
from django.shortcuts import redirect
from django.views.generic import ListView, DetailView
from django.views.generic.base import View
from .models import Movie, Category, Actor, Genre, Reviews
from .forms import ReviewForm


class GenreYear:
    """Get Genre + Year"""
    def get_genres(self):
        return Genre.objects.all()

    def get_years(self):
        return Movie.objects.filter(draft=False).values("year")


class MoviesView(GenreYear, ListView):
    """All movies"""
    model = Movie
    queryset = Movie.objects.filter(draft=False)
    paginate_by = 3  # posts per page


class MovieDetailView(GenreYear, DetailView):
    """Description"""
    model = Movie
    slug_field = "url"
    queryset = Movie.objects.filter(draft=False)


class AddReview(View):
    """Review"""
    def post(self, request, pk):
        form = ReviewForm(request.POST)
        movie = Movie.objects.get(id=pk)
        if form.is_valid():
            form = form.save(commit=False)
            if request.POST.get("parent", None):
                form.parent_id = int(request.POST.get("parent"))
            form.movie = movie
            form.save()
        return redirect(movie.get_absolute_url())


class ActorView(GenreYear, DetailView):
    """Actors & Directors"""
    model = Actor
    template_name = 'movies/actor.html'
    slug_field = "name"


class FilterMoviesView(GenreYear, ListView):
    """Filter"""
    paginate_by = 3

    def get_queryset(self):
        if 'genre' in self.request.GET and 'year' in self.request.GET:
            queryset = Movie.objects.filter(
                Q(year__in=self.request.GET.getlist("year")), Q(genres__in=self.request.GET.getlist("genre"))
            ).distinct()
        else:
            queryset = Movie.objects.filter(
                Q(year__in=self.request.GET.getlist("year")) | Q(genres__in=self.request.GET.getlist("genre"))
            ).distinct()
        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["year"] = ''.join([f"year={x}&" for x in self.request.GET.getlist("year")])
        context["genre"] = ''.join([f"genre={x}&" for x in self.request.GET.getlist("genre")])
        return context


class Search(ListView):
    """Search by name"""
    paginate_by = 3

    def get_queryset(self):
        return Movie.objects.filter(title__icontains=self.request.GET.get("q"))

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["q"] = f'q={self.request.GET.get("q")}&'
        return context

templates/movies/actor.html
{% extends 'movies/base.html' %}
{% load static %}
{% block title %} {{ actor.name }} {% endblock title %}
{% block container %}
    <div class="container py-md-3">
{% endblock container %}

{% block sidebar %}
    <div class="side-bar col-lg-4">
{% endblock sidebar %}

{% block movie %}
    <div class="left-ads-display col-lg-8">
        <div class="row">
            <div class="desc1-left col-md-6">
                <img src="{{ actor.image.url }}" class="img-fluid" alt="">
            </div>
            <div class="desc1-right col-md-6 pl-lg-4">
                <h3 class="editContent">
                    {{ movie.title }}
                </h3>
                <h5 class="editContent"></h5>
                <ul>
                    <li>
                        <span><b>Age:</b> {{ actor.age }} years old</span></li>
                    <li>
                        <span><b>Director:</b>
                            {% for movie in actor.film_director.all %}
                                {{ movie.title }}
                            {% endfor %}
                        </span>
                    </li>
                    <li><span><b>Actor:</b>
                        {% for movie in actor.film_actor.all %}
                            {{ movie.title }}
                        {% endfor %}
                    </span>
                    </li>
                </ul>
            </div>
        </div>
        <div class="row sub-para-w3layouts mt-5">
            <h3 class="shop-sing editContent">
                About {{ actor.name }}
            </h3>
            <p class="editContent">
                {{ actor.description|safe }}
            </p>
        </div>
    </div>
{% endblock movie %}

templates/movies/base.html
{% extends 'base.html' %}
{% block title %} {% endblock title %}
{% block content %}
    <section class="ab-info-main py-md-5 py-4 editContent"
             style="padding-left: 3rem; padding-right: 3rem;">
        {% block container %}
            <div class="container-fluid py-md-3">
        {% endblock container %}
        <div class="row">
            {% block sidebar %}
                <div class="side-bar col-lg-3">
            {% endblock sidebar %}
            {% include 'include/sidebar.html' %}
            </div>
            {% block movie %}
            {% endblock movie %}
        </div>
        </div>
    </section>
{% endblock content %}

templates/movies/movie_detail.html
{% extends 'movies/base.html' %}
{% block title %} {{ movie.title }} {% endblock title %}
{% load static %}
{% block container %}
    <div class="container py-md-3">
{% endblock container %}

{% block sidebar %}
    <div class="side-bar col-lg-4">
{% endblock sidebar %}

{% block movie %}
    <div class="left-ads-display col-lg-8">
        <div class="row">
            <div class="desc1-left col-md-6">
                <img src="{{ movie.poster.url }}" class="img-fluid" alt="">
            </div>
            <div class="desc1-right col-md-6 pl-lg-4">
                <h3 class="editContent">
                    {{ movie.title }}
                </h3>
                <h5 class="editContent"></h5>
                <ul>
                    <li style="list-style: none">
                        <span><b>Year:</b> {{ movie.year }}</span></li>
                    <li style="list-style: none">
                        <span><b>Country:</b> {{ movie.country }}</span>
                    </li>
                    <li style="list-style: none">
                        <span><b>Tagline:</b> {{ movie.tagline }}</span>
                    </li>
                    <li style="list-style: none">
                                    <span><b>Director:</b>
                                        {% for director in movie.directors.all %}
                                            <a href="{{ director.get_absolute_url }}">{{ director.name }} </a>
                                        {% endfor %}
                                    </span>
                    </li>
                    <li style="list-style: none"><span><b>Actors:</b>
                        {% for actor in movie.actors.all %}
                            <a href="{{ actor.get_absolute_url }}">{{ actor.name }}</a>
                        {% endfor %}
                                </span>
                    </li>
                    <li><span><b>Genre:</b>
                        {% for genre in movie.genres.all %}
                            {{ genre.name }}
                        {% endfor %}
                                    </span>
                    </li>
                    <li>
                        <span><b>World premiere:</b> {{ movie.world_premiere }}</span>
                    </li>
                    <li>
                        <span><b>Budget:</b> ${{ movie.budget }}</span></li>
                    <li>
                        <span><b>Fees in USA:</b> ${{ movie.fees_in_usa }}</span></li>
                    <li>
                        <span><b>Fees in World:</b> ${{ movie.fees_in_world }}</span>
                    </li>

                </ul>

                    <div class="share-desc">
                    <div class="share">
                        <h4 class="editContent">
                            Share:</h4>
                        <ul class="w3layouts_social_list list-unstyled">
                            <li>
                                <a href="#" class="w3pvt_facebook editContent">
                                    <span class="fa fa-facebook-f"></span>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="w3pvt_twitter editContent">
                                    <span class="fa fa-twitter"></span>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="w3pvt_facebook editContent">
                                    <span class="fa fa-vk"></span>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
        <div class="row sub-para-w3layouts mt-5">

            <h3 class="shop-sing editContent">
                About {{ movie.title }}
            </h3>
            <p>
                {% for image in movie.movieshots_set.all %}
                    <img src="{{ image.image.url }}" class="img-movie-shots "
                         alt="{{ image.description }}">
                {% endfor %}
            </p>
            <p class="editContent">
                {{ movie.description|safe }}
            </p>

        </div>
        <hr>
        <div class="row">
            <div class="single-form-left">
                <!-- contact form grid -->
                <div class="contact-single">

                    <form action="{% url 'add_review' movie.id %}" method="post" class="mt-4" id="formReview">
                        {% csrf_token %}
                        <input type="hidden" name="parent" id="contactparent" value="">
                        <div class="form-group editContent">
                            <label for="contactcomment" class="editContent">
                                Your comment *
                            </label>
                            <textarea class="form-control border" rows="5" name="text"
                                      id="contactcomment" required=""></textarea>
                        </div>
                        <div class="d-sm-flex">
                            <div class="col-sm-6 form-group p-0 editContent">
                                <label for="contactusername" class="editContent">
                                    Name *
                                </label>
                                <input type="text" class="form-control border" name="name"
                                       id="contactusername" required="">
                            </div>
                            <div class="col-sm-6 form-group ml-sm-3 editContent">
                                <label for="contactemail" class="editContent">
                                    Email *
                                </label>
                                <input type="email" class="form-control border" name="email"
                                       id="contactemail" required="">
                            </div>
                        </div>
                        <button type="submit"
                                class="mt-3 btn btn-success btn-block py-3">
                            Send
                        </button>
                    </form>
                </div>
                <!--  //contact form grid ends here -->
            </div>
        </div>

        {% for review in movie.get_review %}
            <div class="media py-5">
                <img src="{% static 'images/deletedUser.jpg' %}" class="mr-3 img-fluid" alt="image">
                <div class="media-body mt-4">
                    <h5 class="mt-0 editContent">
                        {{ review.name }}
                    </h5>
                    <p class="mt-2 editContent">
                        {{ review.text }}
                    </p>
                    <a href="#formReview" onclick="addReview('{{ review.name }}', '{{ review.id }}')">Answer</a>
                    {% for rew in review.reviews_set.all %}
                        <div class="media mt-5 editContent">
                            <a class="pr-3" href="#">
                                <img src="{% static 'images/deletedUser.jpg' %}" class="img-fluid "
                                     alt="image">
                            </a>
                            <div class="media-body">
                                <h5 class="mt-0 editContent">{{ rew.name }}</h5>
                                <p class="mt-2 editContent">{{ rew.text }}</p>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endfor %}
    </div>
    </div>
    <script>
            function addReview(name, id) {
                document.getElementById("contactparent").value = id;
                document.getElementById("contactparent").innerText = "${name}, ";
            }
    </script>
{% endblock movie %}

templates/movies/movie_list.html
{% extends 'movies/base.html' %}
{% block title %} {% endblock title %}
{% block header %} bg1 {% endblock header %}
{% block movie %}
    <div class="left-ads-display col-lg-9">
        <div class="row">
            {% for movie in movie_list %}
                <div class="col-md-4 product-men">
                    <div class="product-shoe-info editContent text-center mt-lg-4">
                        <div class="men-thumb-item">
                            <img src="{{ movie.poster.url }}" class="img-fluid" alt="">
                        </div>
                        <div class="item-info-product">
                            <h4 class="">
                                <a href="{{ movie.get_absolute_url }}"
                                   class="editContent">
                                    {{ movie.title }}
                                </a>
                            </h4>
                        <div class="product_price">
                                <div class="grid-price">
                                    <span class="money editContent">{{ movie.tagline }}</span>
                                </div>
                        </div>
                        </div>
                                            </div>
                                        </div>
            {% endfor %}
        </div>
        <div class="grid-img-right mt-4 text-right bg bg1" >
            {% include 'include/pagination.html' %}
        </div>
    </div>
{% endblock movie %}